apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lens-selector-git.fullname" . }}
  labels:
    {{- include "lens-selector-git.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  {{- if .Values.config.reposConfig }}
  REPOS_CONFIG: {{ .Values.config.reposConfig | quote }}
  {{- end }}
  {{- if .Values.config.gitRepoUrl }}
  GIT_REPO_URL: {{ .Values.config.gitRepoUrl | quote }}
  {{- end }}
  {{- if .Values.config.gitBranch }}
  GIT_BRANCH: {{ .Values.config.gitBranch | quote }}
  {{- end }}
  {{- if .Values.config.lensFilePath }}
  LENS_FILE_PATH: {{ .Values.config.lensFilePath | quote }}
  {{- end }}
  CACHE_TTL_MINUTES: {{ .Values.config.cacheTtlMinutes | quote }}
  {{- if .Values.config.lensReposTempDir }}
  LENS_REPOS_TEMP_DIR: {{ .Values.config.lensReposTempDir | quote }}
  {{- end }}
